consensus-shipyard/ipc-solidity-actors

src/SubnetActor.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/102 and https://github.com/consensus-shipyard/ipc-solidity-actors/issues/103 .

Fix reentrancy vulnerabilities

---

src/Gateway.sol

This PR fixes a potential vulnerability to reentrancy attacks - https://github.com/consensus-shipyard/ipc-solidity-actors/issues/94.
To eliminate a race, I just use the values of the message instead of one.

Fix reentrancy

---

Makefile
src/constants/Constants.sol

This PR: 
- Removes constant that are available in the `fevmate` library. 
- Fixes slight bug in `Makefile`.

Remove unused constants and fix Makefile

---

Makefile
ops/README.md
ops/compile-abi.sh

This PR adds a handy makefile rule to help with compiling the ABI of the contracts.

add makefile rule to compile actors abi

---

Makefile
hardhat.config.ts
ops/deploy.sh
scripts/deploy-gateway.template

This PR makes `chainID` configurable depending on the network where the IPC gateway is deployed, and adds a timeout when deploying in calibration to avoid the deployment transaction timing out.

fix deployment in calibration and config chainID

---

ops/deploy.sh
scripts/deploy-gateway.template
src/Gateway.sol
test/Gateway.t.sol

This PR: 
- Includes a `listSubnet` function in the gateway (the size have increased so to deploy the contract now we need to comment `propagate`, `setMembership` and `sendCross` which won't be supported until the next version of IPC)
- Add support for mainnet in the deploy scripts. 
- Add a new error of `MethodNotSupportedYet` for the mainnet deployment

add list subnets and fix deploy

---

ops/compile-abi.sh
scripts/deploy-gateway.template

Fix bug for which including tests in the abi compilation led to the intermediate representation created by the compiler with `--via-ir` reached the depth stack of the IR. 
In the process, I got a quick fix for which the deployment of the gateway also notifies about the chainID of the network where the gateway is being deployed.

fix bug in compile-abi and deploy-gateway

---

src/SubnetActorDiamond.sol

Bottom up checkpoint period is not set when subnet was created. This PR fixes that.

Fix bottom up checkpoint period

---

.github/workflows/branch-check.yaml
README.md

With the diamond implementation of the contracts we are going to include a breaking change that may break the agent and other dependencies. To avoid this from happening, let's use the same branching strategy that we are using in the rest of the IPC repos.

add development branch

---

src/gateway/GatewayGetterFacet.sol
test/GatewayDiamond.t.sol
test/SubnetActorDiamond.t.sol

This PR:
- disable printing
- remove unused functions

Minor fixes

---

scripts/deploy-registry.template

This PR fixes a bug for which the registry couldn't be deployed because it was missing the right libraries. It also comments a set of outputs that were a bit confusing, we are only interested in the gateway and registry addresses to configure our agent.

fix: deploy registry

---

Makefile
README.md
hardhat.config.ts
ops/chain-id.sh
ops/deploy.sh
scripts/deploy-gateway.template

This PR updates the deployment scripts in a way that by default or if `NETWORK=auto` is enabled, the deployment scripts automatically fetch the chain ID of the network `RPC_URL` is pointing to in order to deploy the IPC contracts with the right ID.

get chain-id automatically in deploy-ipc

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
src/gateway/GatewayGetterFacet.sol
src/lib/LibGateway.sol
src/lib/LibGatewayActorStorage.sol
src/structs/Subnet.sol
test/GatewayDiamond.t.sol

To integrate with Fendermint, we are arranging the top down checkpoint by height. Key changes:
- Changing `topDownMsgs` from array to `mapping(uint256 =>array)` with block height as key.
- Update all the getter functions, removed unused ones.

Arrange top down messages by height

---

Makefile
README.md

Some unit tests require `eth-abi` python module to work. Previously `make test` assumes `eth-abi` has already been installed, now we add install `eth-abi` into `make install-dev`.

Add install eth-abi to make test

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
src/gateway/GatewayRouterFacet.sol
src/lib/LibGateway.sol

When committing parent finality, return the previous finality. This is for fendermint to validate the finalities are consistent.

Return previous finality

---

binding/src/subnet_actor_manager_facet.rs
src/subnet/SubnetActorManagerFacet.sol

Fixes an error discovered by https://github.com/consensus-shipyard/fendermint/pull/319
Follow up to https://github.com/consensus-shipyard/ipc-solidity-actors/pull/257
The reason we can't allow 0 in unstake is because if we do, the next checkpoint fails:
```
checkpoint submission should succeed: CallError { exit_code: ExitCode { value: 33 }, failure_info: Some(MessageBacktrace(Backtrace { frames: [Frame { source: 64, method: 6, code: ExitCode { value: 33 }, message: "contract reverted" }, Frame { source: 64, method: 3844450837, code: ExitCode { value: 33 }, message: "contract reverted" }, Frame { source: 120, method: 6, code: ExitCode { value: 33 }, message: "contract reverted" }, Frame { source: 120, method: 3844450837, code: ExitCode { value: 33 }, message: "contract reverted" }], cause: …
```

FIX: Cannot unstake 0

---

src/gateway/GatewayManagerFacet.sol
src/gateway/GatewayMessengerFacet.sol

This PR fixes a bug for which burns were being burnt when [sending arbitrary cross-net message,](https://github.com/consensus-shipyard/ipc-solidity-actors/blob/3f72d21d0ad601fbb673b6a9bc650d14f7be9c9f/src/gateway/GatewayMessengerFacet.sol#L41) but not when a simple `release` message was being triggered.

FIX: funds weren't being burnt in release

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
src/errors/IPCErrors.sol
src/gateway/GatewayRouterFacet.sol
src/lib/LibGateway.sol

Remove the check on `checkpointInfo.threshold` due to:
- 0 threshold is also valid threshold.
- Checkpoint info is created together with checkpoint, as long as checkpoint is created, checkpoint info will be created. Checking checkpoint should be enough.

Remove check

---

Makefile
binding/build.rs

Forgot to pass `$OUTPUT` to the bindings build.

CI: Pass OUTPUT in rust-bindings

---

scripts/util.ts

`make` on dev is currently failing and this fixes it. ganache-core was deprecated for ganache

ganache-core is deprecated for ganache

---

.github/workflows/bindings.yml
ops/commit-abi.sh
ops/commit-rust-binding.sh

Not running the `bindings.yaml` workflow on `push` because it triggers itself recursively.

CI: No bindings on push

---

src/constants/Constants.sol
src/lib/AccountHelper.sol
test/unit/AccountHelper.t.sol

The logic here wasn't completely correct. A BLS account in FEVM would look like an account. It'll return true for precompiles. An inexistent address (which could later become an account) will return false.
Not sure if these behaviours were intended, since the method is not documented. But given that it's also not used, it's better to drop it so it doesn't get used in this form.

cleanup: remove unused `AccountHelper#isAccount` predicate.

---

.github/workflows/test.yml

I started noticing yesterday that our code coverage test is flaky and failing incorrectly some of the time.
This patch is very duct tape, but it runs it once and if and only if it fails it runs it again. If we are failing this test 10% of the time, running it twice could mean that it will only fail 100%-90%*90%=1% of the time.
Assuming this flakiness is independently happening due to a random bug in forge. 
We should also understand why this is failing on a deeper level and fix it, and this fix may not make a change if somehow it is consistently failing, but the effort is really low and is a good chance at helping with almost no downside. 
Currently we are merging into dev with this test failing, so our current situation deserves some sort of short term patch
here's an example commit that …

Update test.yml - coverage test is failing incorrectly sometimes

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
src/SubnetActorDiamond.sol
src/errors/IPCErrors.sol
src/gateway/GatewayManagerFacet.sol
src/lib/LibStaking.sol
src/subnet/SubnetActorManagerFacet.sol
test/integration/GatewayDiamond.t.sol
test/integration/SubnetActorDiamond.t.sol

Bootstrap federated validation by setting the genesis validators. It does a check on the `bootstrapped` field. If `bootstrapped`, then we call `postBootstrapSetFederatedPower` else we call `preBootstrapSetFederatedPower`. In `preBootstrapSetFederatedPower`, we also update the genesis validators as well.

Bootstrap federated validation

---

binding/build.rs

Expose lib quorum in `binding` folder so that downstream repos can import this.

Expose lib quorum

---

binding/build.rs

With the breakdown of `RouterFacet` into multiple smaller facets, the rust binding build file needs to updated with latest changes, otherwise it's broken.

fix rust binding

---

test/IntegrationTestBase.sol
test/IntegrationTestPresets.sol
test/integration/GatewayDiamondToken.t.sol
test/integration/L2GatewayDiamond.t.sol
test/invariants/GatewayActorInvariantTests.t.sol
test/invariants/GatewayActorProperties.sol
test/invariants/handlers/GatewayActorHandler.sol

This PR establishes a skeleton for future invariant tests for GatewayActor.
The main idea is to define all basic properties of the gatewayActor and be able to apply them to many different Gateway instances with different configurations.

Add skeleton for GatewayActor invariants
