consensus-shipyard/ipc-solidity-actors

src/Gateway.sol
src/interfaces/IGateway.sol
src/lib/CrossMsgHelper.sol
test/CrossMsgHelper.t.sol
test/Gateway.t.sol

* add `whitelistPropagator` method that whitelists a series of addresses as propagator of a cross net message
* add `propagate` method that propagates the stored postbox item

Implement propagate methods

---

package-lock.json
package.json
scripts/README.md
scripts/deploy-registry.ts
src/SubnetRegistry.sol

Support subnet actor registry that deploys subnet contract from registry contract. At the same time, it also tracks the deployed subnet onchain.

Add subnet registry

---

script/Deployer.sol
src/Gateway.sol
src/SubnetActor.sol
src/enums/ConsensusType.sol
test/Gateway.t.sol
test/SubnetActor.t.sol

Related: https://github.com/consensus-shipyard/ipc-actors/pull/122
//cc @cryptoatwill

chore: remove unused consensusTypes

---

scripts/deploy-gateway.ts

Update the subnet id construction in deployment typescript.

Fix gateway deployment script

---

scripts/deploy-gateway.ts
src/SubnetActor.sol

List all validators in a subnet contract. In the future we can add in pagination, but it should be good for now.

List all validators

---

README.md
package.json

This PR adapts README and package.json.

Change intro

---

src/Gateway.sol
src/SubnetActor.sol
src/lib/EpochVoteSubmissionHelper.sol
src/lib/SubnetIDHelper.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/95 and https://github.com/consensus-shipyard/ipc-solidity-actors/issues/106

Minor gas optimisations

---

src/Gateway.sol
src/Voting.sol
src/lib/CheckpointHelper.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/100

Use logical if statements

---

src/SubnetRegistry.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/99

Make gateway address immutable

---

.solhint.json
Makefile
package-lock.json
package.json
remappings.json
slither.config.json
src/Gateway.sol
src/SubnetActor.sol
src/Voting.sol
src/lib/AccountHelper.sol
src/lib/CheckpointHelper.sol

This PR enables linting using `solhint` and security checks using `slither`. You have to run them manually using
```
make lint
make check
```

Enable basic linting

---

src/Gateway.sol
src/SubnetRegistry.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/101 and partially https://github.com/consensus-shipyard/ipc-solidity-actors/issues/56

Check gateway address

---

src/Gateway.sol
src/SubnetActor.sol
src/SubnetRegistry.sol
src/Voting.sol
src/lib/SubnetIDHelper.sol
test/Gateway.t.sol

Optimise loop

---

Makefile
README.md
src/Gateway.sol
src/constants/Constants.sol
src/interfaces/IGateway.sol
src/lib/SubnetIDHelper.sol
test/Gateway.t.sol

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/90

Update sendCross method

---

.solhint.json
script/Deployer.sol
src/Gateway.sol
src/SubnetActor.sol
src/SubnetRegistry.sol
src/Voting.sol
src/interfaces/IGateway.sol
src/interfaces/ISubnetActor.sol
src/lib/AccountHelper.sol
src/lib/CheckpointHelper.sol
src/lib/CrossMsgHelper.sol
src/lib/EpochVoteSubmissionHelper.sol
src/lib/ExecutableQueueHelper.sol
src/lib/StorableMsgHelper.sol
src/lib/SubnetIDHelper.sol
src/structs/Checkpoint.sol
src/structs/EpochVoteSubmission.sol
src/structs/Subnet.sol
test/SubnetActor.t.sol

This PR reduces the size of the main contracts making it possible to deploy the Gateway contract.

Reduce contract sizes

---

src/Gateway.sol
src/SubnetActor.sol

Migrate bottom up checkpoint query from gateway to subnet actor contract.

Migrate bottom up checkpoints query to subnet actor

---

src/Gateway.sol
src/SubnetActor.sol
test/Gateway.t.sol

Get top down messages also by nonce.

Get top down messages by nonce

---

src/Gateway.sol
src/interfaces/IGateway.sol
test/Gateway.t.sol

Remove postbox owners so that anyone can call `propagate`. Related to #134

Remove postbox owners

---

src/Gateway.sol

This is for issue #143 so that top down checkpoint submission for fevm can be implemented.

Query the latest applied top down nonce

---

.github/workflows/sast.yaml
.github/workflows/storage.yml
.github/workflows/test.yml
.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
Makefile
hardhat.config.ts
package-lock.json
package.json

This PR fixes https://github.com/consensus-shipyard/ipc-solidity-actors/issues/147.

Add storage checker

---

src/gateway/GatewayGetterFacet.sol
src/subnet/SubnetActorGetterFacet.sol

Implement some missing getter functions after integration with `ipc-agent`.

Diamond patches

---

src/SubnetRegistry.sol
src/diamond/DiamondLoupeFacet.sol
test/SubnetRegistry.t.sol

This PR fixes several issues found by Slither.

Subnet registry fixes

---

src/subnet/SubnetActorGetterFacet.sol

Using multiples of bottom up checkpoint period to list bottom up checkpoints.

Fix list bottom up

---

README.md

This PR adds links to the main documents.

Add docs to README.md

---

src/GatewayDiamond.sol
src/gateway/GatewayGetterFacet.sol
src/lib/LibDiamond.sol
src/lib/LibGateway.sol
src/subnet/SubnetActorGetterFacet.sol

This PR introduces several optimizations to reduce gas costs.

Improve loops

---

ops/compile-abi.sh

Update ops script

---

.solhint.json
package-lock.json
package.json
src/GatewayDiamond.sol
src/SubnetActorDiamond.sol
src/SubnetRegistry.sol
src/errors/IPCErrors.sol
src/gateway/GatewayGetterFacet.sol
src/gateway/GatewayManagerFacet.sol
src/gateway/GatewayMessengerFacet.sol
src/gateway/GatewayRouterFacet.sol
src/lib/CrossMsgHelper.sol
src/lib/LibDiamond.sol
src/lib/LibGateway.sol
src/lib/LibGatewayActorStorage.sol
src/lib/LibSubnetActorStorage.sol
src/lib/StorableMsgHelper.sol
src/subnet/SubnetActorGetterFacet.sol
src/subnet/SubnetActorManagerFacet.sol
test/GatewayDiamond.t.sol
test/StorableMsgHelper.t.sol

This PR updates the code related to new Solhint's checks.

Update solhint and fix false positives

---

src/errors/IPCErrors.sol
src/lib/LibVoting.sol
src/subnet/SubnetActorGetterFacet.sol
src/subnet/SubnetActorManagerFacet.sol
test/SubnetActorDiamond.t.sol

This PR adds `setValidatorNetAddr` and `setValidatorWorkerAddr` method.

Add setValidatorNetAddr

---

src/errors/IPCErrors.sol
src/gateway/GatewayManagerFacet.sol
src/subnet/SubnetActorGetterFacet.sol
test/SubnetActorDiamond.t.sol

This PR adds a pagination method for validators.

Add pagination

---

src/GatewayDiamond.sol
src/SubnetActorDiamond.sol
src/errors/IPCErrors.sol
src/lib/LibVoting.sol
test/GatewayDiamond.t.sol
test/LibVoting.t.sol
test/SubnetActorDiamond.t.sol

This PR removes min values for collateral and submission period according to the https://github.com/consensus-shipyard/fendermint/pull/267#issuecomment-1718091638

Remove min params

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
binding/src/gateway_getter_facet.rs
src/gateway/GatewayGetterFacet.sol
test/GatewayDiamond.t.sol

To help detect chain reorg, returning block hashes as required.

Chain reorg detection

---

.storage-layouts/GatewayActorModifiers.json
.storage-layouts/GatewayDiamond.json
.storage-layouts/SubnetActorDiamond.json
.storage-layouts/SubnetActorModifiers.json
binding/src/gateway_getter_facet.rs
src/gateway/GatewayGetterFacet.sol
test/GatewayDiamond.t.sol

Remove block hash from query top down messages.

remove block hash

---

.github/workflows/bindings.yml
.github/workflows/test.yml
Makefile
src/SubnetRegistry.sol
src/gateway/GatewayGetterFacet.sol

It fixes several Slither findings and https://github.com/consensus-shipyard/ipc-solidity-actors/issues/233

Fix slither findings

---

src/subnet/SubnetActorManagerFacet.sol

Fixes for problems discovered in https://github.com/consensus-shipyard/fendermint/pull/319

Integration testing fixes

---

scripts/deploy-gateway.template.ts
scripts/deploy-libraries.ts
scripts/deploy-registry.template.ts
scripts/deploy-sa-diamond.ts

Remove checkpoint helper from deployment.

remove CheckpointHelper

---

test/invariants/SubnetRegistryInvariants.t.sol

A workaround for invariant tests

Fix invariant test

---

test/SubnetActorDiamond.t.sol

This PR fixes a bug related vm's prank call.

Fix prank in test

---

.github/workflows/bindings.yml

Fix syntax error in `bindings.yaml`

Fix bindings.yaml

---

.github/workflows/bindings.yml

Fix bindings.yaml syntax

---

src/gateway/GatewayRouterFacet.sol
test/IntegrationTestBase.sol
test/integration/GatewayDiamond.t.sol
test/integration/GatewayL2Diamond.t.sol

Changes are atomized. See commit log for details.

improvements in xnet message application code paths

---

src/GatewayDiamond.sol
src/SubnetRegistryDiamond.sol
src/gateway/GatewayManagerFacet.sol
src/gateway/GatewayRouterFacet.sol
src/interfaces/ISubnetActor.sol
src/lib/LibGateway.sol
src/lib/LibStaking.sol
src/lib/LibSubnetActorStorage.sol
src/structs/Subnet.sol
src/subnet/SubnetActorManagerFacet.sol

This PR removes unused imports.

Clean imports

---

test/integration/SubnetActorDiamond.t.sol

Adding tests for static validation.

Adding tests for static validation

---

src/subnet/SubnetActorManagerFacet.sol

Comment sa manager facet

---

scripts/deploy-libraries.ts

missed this line which exports the lib

bugfix need to export libquorom
